name       : kdenlive
version    : 16.12.3
release    : 15
source     :
    - http://download.kde.org/stable/applications/16.12.3/src/kdenlive-16.12.3.tar.xz : a04d5a957bedc31834379122e597ba55e1474246376d661c535979007a76eafc
license    : GPL-2.0
component  : multimedia.video
summary    : Video editing application, based on MLT Framework and KDE Frameworks 5.
description: |
    Video editing application, based on MLT Framework and KDE Frameworks 5.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKF5Attica)
    - pkgconfig(libv4l2)
    - pkgconfig(mlt-framework)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - karchive-devel
    - kauth-devel
    - kbookmarks-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kfilemetadata-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - shared-mime-info
    - solid-devel
    - sonnet-devel
rundeps    :
    - breeze
    - breeze-icons
    - dvgrab
    - frei0r
    - kinit
    - qt5-quickcontrols
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
