name       : kdenlive
version    : 19.12.0
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.0/src/kdenlive-19.12.0.tar.xz : 4f3f434a89169a948c3ea402df8333ebaef2f24dc23247be0244538c856c7717
homepage   : https://kde.org/applications/multimedia/org.kde.kdenlive
license    : GPL-2.0-or-later
component  : multimedia.video
optimize   : lto
summary    : Video editing application, based on MLT Framework and KF5
description: |
    Video editing application, based on MLT Framework and KDE Frameworks 5.
builddeps  :
    - pkgconfig(libKF5Attica)
    - pkgconfig(libv4l2)
    - pkgconfig(mlt-framework)
    - pkgconfig(Qt5MultimediaWidgets)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - karchive-devel
    - kcodecs-devel
    - kconfigwidgets-devel
    - kcrash-devel
    - kdeclarative-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kfilemetadata-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - purpose-devel
    - rttr-devel
    - shared-mime-info
rundeps    :
    - breeze
    - breeze-icons
    - dvgrab
    - frei0r
    - qt5-quickcontrols
    - qt5-quickcontrols2
setup      : |
    %patch -p1 < $pkgfiles/0001-Unset-QPA_PLATFORMTHEME-to-prevent-starting-with-gtk.patch
    %patch -p1 < $pkgfiles/0001-Add-StartupWMClass-to-desktop-file.patch
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
