name       : kdenlive
version    : 22.04.0
release    : 82
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/kdenlive-22.04.0.tar.xz : 66147b2f1a2cf6f05eda15e4cc3e9d9b126d2dbcc187ecc6d78dea2c7b2c6d79
homepage   : https://kde.org/applications/multimedia/org.kde.kdenlive
license    : GPL-2.0-or-later
component  : multimedia.video
summary    : Video editing application, based on MLT Framework and KF5
description: |
    Video editing application, based on MLT Framework and KDE Frameworks 5.
optimize   : lto
builddeps  :
    - pkgconfig(libv4l2)
    - pkgconfig(mlt-framework-7)
    - pkgconfig(Qt5MultimediaWidgets)
    - pkgconfig(Qt5NetworkAuth)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - karchive-devel
    - kcrash-devel
    - kdeclarative-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kfilemetadata-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - ktextwidgets-devel
    - purpose-devel
rundeps    :
    - breeze
    - breeze-icons
    - dvgrab
    - frei0r
    - qt5-quickcontrols
    - qt5-quickcontrols2
setup      : |
    %patch -p1 < $pkgfiles/0001-Unset-QPA_PLATFORMTHEME-to-prevent-starting-with-gtk.patch
    %patch -p1 < $pkgfiles/0001-Add-StartupWMClass-to-desktop-file.patch
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Remove doc
    rm -rf $installdir/usr/share/doc
