name       : kdenlive
version    : 20.08.2
release    : 64
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.2/src/kdenlive-20.08.2.tar.xz : 535df45a148f0f94271e045ef0c93575fded83da7a2b727aeaf90e61e1d7c418
homepage   : https://kde.org/applications/multimedia/org.kde.kdenlive
license    : GPL-2.0-or-later
component  : multimedia.video
optimize   : lto
summary    : Video editing application, based on MLT Framework and KF5
description: |
    Video editing application, based on MLT Framework and KDE Frameworks 5.
builddeps  :
    - pkgconfig(libKF5Attica)
    - pkgconfig(libv4l2)
    - pkgconfig(mlt-framework)
    - pkgconfig(Qt5MultimediaWidgets)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - karchive-devel
    - kcodecs-devel
    - kconfigwidgets-devel
    - kcrash-devel
    - kdeclarative-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kfilemetadata-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - purpose-devel
    - rttr-devel
    - shared-mime-info
rundeps    :
    - breeze
    - breeze-icons
    - dvgrab
    - frei0r
    - qt5-quickcontrols
    - qt5-quickcontrols2
setup      : |
    %patch -p1 < $pkgfiles/0001-Unset-QPA_PLATFORMTHEME-to-prevent-starting-with-gtk.patch
    %patch -p1 < $pkgfiles/0001-Add-StartupWMClass-to-desktop-file.patch
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Remove doc
    rm -rf $installdir/usr/share/doc
